apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-world-mduser016
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello-world-mduser016
spec:
  env:
  - name: APP_MESSAGE
    value: Hello World!
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/hello-world-mduser016
      ref:
        branch: main
